### ISSUE TITLE
package.json build script places files incorrectly

### ISSUE THREAD

**Issue by hut8** [DomoApps/advanced-sample-app#23]
Thanks very much for this sample app. It's very useful and well thought-out.

Minor issue: running `npm run build`, which is:
```
rm -rf ./dist && NODE_ENV=production ./node_modules/.bin/webpack && cp -r domo/ dist/
```
results in the `dist` folder containing a `domo` folder, which contains the thumbnail and manifest.json. Another script, `upload`, has:

```
npm run build && cd dist/ && domo publish && cd ..
```

Because `manifest.json` is in `dist/domo` and not just `dist/`, that ends up causing this error:

```
X No manifest.json file in this directory
Please publish from a directory containing a Custom App design manifest.json file
```

Perhaps the `build` script could just run `cp domo/* dist/` instead?

**Comment by jpumford** [comment]
Hey, thanks!

I'm going to move this issue over to `starter-kit`, we'll take a look at it over there.
https://github.com/DomoApps/starter-kit/issues/60

**Comment by hut8** [comment]
I'll open a PR with change from https://github.com/DomoApps/starter-kit/pull/62
